# Generated by Django 4.0.3 on 2022-04-07 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Group number')),
                ('academic_year', models.CharField(max_length=4, verbose_name='Academic year in roman numerals')),
                ('programme', models.CharField(max_length=32, verbose_name='Group programme')),
                ('student_count', models.IntegerField(verbose_name='Number of students in the group')),
            ],
            options={
                'db_table': 'group',
                'unique_together': {('number', 'academic_year', 'programme')},
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('academic_rank', models.CharField(choices=[('PROF.', 'Professor'), ('A/PROF.', 'Associate professor'), ('LECT.', 'Lecturer'), ('A/LECT.', 'Assistant lecturer')], max_length=8)),
            ],
            options={
                'db_table': 'lecturer',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='Student full name')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.group')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Course name')),
                ('credit_count', models.FloatField()),
                ('groups', models.ManyToManyField(related_name='courses', to='timetable.group')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.lecturer')),
            ],
            options={
                'db_table': 'course_unit',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8, verbose_name='Room number')),
                ('capacity', models.IntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.faculty')),
            ],
            options={
                'db_table': 'classroom',
            },
        ),
    ]
